### ISSUE TITLE
Update RGB templates repository

### ISSUE THREAD

**Issue by jvanderleeuw** [AgPipeline/computing-pipeline#153]
**Task to do**
Update template_rgb_plot within the templates repository to reflect the recently updated AgPypeline template_rgb_plot repo. Also ensure that documentation is up to date and get rid of unnecessary files

**Reason**
Increase usability of the templates repo

**Result**
Repository will be cleaner and updated

This differs from template_rgb_plot at https://github.com/AgPipeline/template-rgb-plot because it uses a separate templates folder to run tests rather than doing it all through the separate algorithm_rgb.py and testing.py files. The idea at the moment is to create a versatile testing file that can handle multiple types of image data

The base files contained in this repository and template_rgb_plot are the same, but the reason that this repo is different is because of the testing folder

**Comment by Chris-Schnaufer** [comment]
Just to be clear, the testing file is for users to test their algorithms out with?

Would it be better if the testing code was in a library and the testing.py file (the file doesn't need to have that name) makes use of the library and handles any differences between what's in the library and the template code? For example, loading RGB data instead of Lidar.

If this isn't done, won't the testing.py file need to contain ways to load every different type of 
 supported data file, even when it's not needed? For example, the RGB testing file would now need to support lidar as well, even if the developer of the RGB algorithm never uses Lidar?

**Comment by jvanderleeuw** [comment]
I think I see. Would that mean having a testing.py script as a library in and of itself and then having templates import that library and then use it. The templates could have their own testing.py files if needed/wanted for extra methods, but could use the library one for the default testing

**Comment by Chris-Schnaufer** [comment]
I don't think the testing scripts should in a library. I think that there should be more than one script to handle the differences between Image data and Lidar data

**Comment by Chris-Schnaufer** [comment]
Moved to Ready pipeline

@jvanderleeuw Can you comment on the status of this?

**Comment by jvanderleeuw** [comment]
Issue closed due to vagueness and overlap with [#87](https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/87), [#42](https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/42), and [#44](https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/44)
