### ISSUE TITLE
Review Emily's notes on the pipeline alpha user

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#339]
This HackMD [note](https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/HkIAu2QOP) doesn't cover everything I've worked on and written rough notes for, but I wanted to make sure I was on the right track for what yall had in mind for me to do and take note of. 

Original scope defined in #275

The focus is on going through the documentation, following steps, and identifying what is clear, what is not, what works/ doesnt/ and what could be done to ensure user success.

**Comment by dlebauer** [comment]
This is great! I've made a few comments in the document on follow up issues

**Comment by Chris-Schnaufer** [comment]
Thanks for doing this! I have added some notes and follow up suggestions. The main problem (in my mind) with the way things are now is that there are so many places to start out in. There's the legacy TERRA REF repo, the legacy az-digitalag/https://github.com/az-digitalag/Drone-Processing-Pipeline repo, the OSF site, the repos in the AgPipeline organization, and the GitHub IO pages.

Mapping out what documentation should reside should be done and would help guide users to finding what they want. The current approach is to house technical documentation on GitHub with less technical documentation on OSF.

Perhaps we can also generate a list of Google search phrases and terms that we would like this project associated with so that we can make it easier for people to find it?

**Comment by dlebauer** [comment]
link follow up issues before closing

**Comment by MagicMilly** [comment]
Breaking down the rest of ticket #340 into manageable chunks (Issues #350 and #349) for next Sprint follow-up
