### ISSUE TITLE
Schedule first meeting for DPP group

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#345]
- [x] Decide on rough agenda for first meeting
- [x] Send out e-mail to check for availability
- [x] Choose date/time that works for most people
- [x] Subscribe new members
- [x] Draft e-mail for Chris to review
- [x] Send invitation e-mail with Zoom info

**Comment by MagicMilly** [comment]
For the few people who filled out the when2meet, Mondays at 4 PM was the best time. ~Am still waiting on more names and e-mails before scheduling the first meeting.~

Have Matt Rahr's list and Chris' original list. Once I combine then, will work on e-mail draft for Chris to review.

**Comment by MagicMilly** [comment]
Meeting scheduled for Monday, Nov 23 at 4 PM

**Comment by dlebauer** [comment]
TODO

*  [x] Define agenda
   * [x] fill out [this meeting planning canvas](https://app.zenhub.com/files/216677713/8598b306-909a-4862-a412-03384833efbb/download)
*  [ ] Send reminder and request RSVP (either via zoom reg) on Friday - maybe also Monday morning?

**Comment by Chris-Schnaufer** [comment]
[https://app.zenhub.com/files/216677713/3e1a0ac9-58cb-4316-a6e3-2e43bc7dd1cb/download](https://app.zenhub.com/files/216677713/3e1a0ac9-58cb-4316-a6e3-2e43bc7dd1cb/download)

Agenda:
Introduce Agenda - 2 min
Introduce Proposed objectives of group w/ discussion - 8 min
Presentations - 10 min each for 40 min max
Determine frequency of meetings - 5 min
Wrap up - 5 min

Proposed Objectives (pertaining to):
- Education: each meeting have at least one presentation on the work someone is doing, or focus on an aspect of using drones. (a methodology presentation for example)
- Help: develop a community to answer questions and provide help for drone users
- Growth: develop ways of capturing best practices and methods so that others can make use of and/or adapt them

**Comment by dlebauer** [comment]
Looks great, only thing I would change is 

"Presentations - 10 min each for 40 min max" to "Introductions / optional presentations 5-10 min each"

"Presentations" is a pretty high bar; I doubt we will get any that people haven't signed up for. Perhaps ask people if they want to present in the RSVP?

**Comment by Chris-Schnaufer** [comment]
Perhaps we could make it low-bar by just saying that after any presentations people can openly talk about what they're doing for 6-10 min? Reworded of course

**Comment by dlebauer** [comment]
works for me
