### ISSUE TITLE
Update permissions and repos for improving DPP documentation

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#354]
@Chris-Schnaufer I'm unable to make some of the changes requested by you and David due to lack of permissions. Could you please:
- [x] Add me as an editor/contributor to the [OSF](https://osf.io/xdkcy/) (I have also requested access directly on OSF)
- [x] Either add me as a contributor to the terra-ref drone pipeline [repo](https://github.com/terraref/drone-pipeline) or perform these tasks:
    - [x] Deprecate and archive repo
    - [x] Update the README to indicate these changes and point to a new repository (Ag Pipeline Organization-info [repo](https://github.com/AgPipeline/Organization-info))?

**Comment by dlebauer** [comment]
* The TERRA REF repository has been archived, with a pointer to the OSF wiki https://github.com/terraref/drone-pipeline/blob/master/README.md
* @Chris-Schnaufer should this repository be archived as well? https://github.com/az-digitalag/Drone-Processing-Pipeline ... or what is its purpose?
   * or can we just delete these repositories since they don't really have a user / contributor base (and confusingly aren't forked from one another)?

**Comment by Chris-Schnaufer** [comment]
@dlebauer @MagicMilly I have archived the az-digitalag repositories that are out of data after pointing them to the OSF site

**Comment by MagicMilly** [comment]
Thank you Chris!
