### ISSUE TITLE
Redirect makeflow pull requests to AgPipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#7]
- [x] agpipeline/cleanmetadata:latest
- [x] agpipeline/bin2tif:latest
- [x] agpipeline/soilmask:latest
- [x] agpipeline/fieldmosaic:latest
- [x] agpipeline/canopycover:latest
- [x] Rebase PR over this repo

**Comment by julianpistorius** [comment]
@Chris-Schnaufer - I'm not sure which repo in the @AgPipeline to direct the Makeflow PR to.

When we discussed this at the meeting I was under the impression that you had moved the entire https://github.com/Chris-Schnaufer/agp-test repo over to the @AgPipeline organization and I just had to 'redirect' the PR to the new copy of the `agp-test` repo. I can't find that repo in either the @AgPipeline or @az-digitalag organization.

1. Do you want me to move the `agp-test` repo over to the @AgPipeline organization?
2. Or did you mean for me to modify the PR to work against one or both of the these repos?: 
    - https://github.com/AgPipeline/computing-pipeline  
    - https://github.com/AgPipeline/drone-pipeline

Item 1 is trivial (which is why I gave it a '1' for estimate). 

Item 2 has unknown complexity. I haven't looked closely at either of those code-bases yet. 

Best-case scenario: They're mostly the same as the https://github.com/Chris-Schnaufer/agp-test repo. In this case I will only need to make minor changes and some testing. Say 2-3 as an estimate. 

Worst case scenario: Those two repose are quite different from `agp-test`. In that case I will need to do some refactoring to get Makeflow to work, in addition to thorough testing. Say 4-5 as an estimate.

I can start (and maybe finish) either of those options today if you let me know before lunch.

Thanks!

**Comment by Chris-Schnaufer** [comment]
I'll call

**Comment by julianpistorius** [comment]
Ahah! That makes sense. Thank you. I can do that. Thanks @Chris-Schnaufer 

P.S. Please excuse me from our on-on-one catchup this afternoon. I have a lot to get done by Monday! Let's try to catch up on Monday afternoon. Thanks!

**Comment by julianpistorius** [comment]
@Chris-Schnaufer Update: I was able to get the metadata cleaning steps working with the new container:

https://github.com/Chris-Schnaufer/agp-test/pull/1/commits/e0bcbd95a08e708c9aae96a553a2b9fbb0191032

The API of the bin2tif container has changed and something in that Makeflow step is breaking now. I'm not sure, but it seems to need the input and output to the in the same directory (??). I might need your help to figure it out.

**Comment by julianpistorius** [comment]
Chat with @Chris-Schnaufer on 2019-11-19:

- Workspace parameter is where the output goes to
- Input is files or folders as positional arguments at the end (Point this at where the .bin files are)

**Comment by julianpistorius** [comment]
@Chris-Schnaufer I integrated `bin2tif` & `soilmask` into the Makeflow.

Now I need your help with `fieldmosaic` and `canopycover`.

Maybe @max-zilla could help as well?

**Comment by julianpistorius** [comment]
Here is the current state of the Makeflow:

https://github.com/julianpistorius/agp-test/commit/1d1c29ae6f53af50b5e7c6dae14decc21491a651

**Comment by julianpistorius** [comment]
I think I've figured out the problem I ran into with `fieldmosaic`. It was partly due to a bug in the code, and partly PEBCAK.

I will finish this on Monday, and make a PR to fix the bug.

**Comment by julianpistorius** [comment]
Makeflow step for `fieldmosaic` is done: https://github.com/julianpistorius/agp-test/commit/180a4e5827ee842038cb3bda413a768b3d9bfe19

It depends on `agpipeline/fieldmosaic:latest` image being built with following PR for `fieldmosaic`: https://github.com/AgPipeline/transformer-fieldmosaic/pull/4

Questions for @Chris-Schnaufer: 

- [ ] How and when do the Docker images get updated?
- [ ] Will the mosaic bounds for MAC Gantry pipeline always be: `"-111.9750963 33.0764953 -111.9747967 33.074485715"`?

**Comment by julianpistorius** [comment]
Canopy cover is done:

https://github.com/julianpistorius/agp-test/commit/741fc8741777d36c478458cf78f0f0bdfe8a29ec

**Comment by julianpistorius** [comment]
Current state: https://github.com/julianpistorius/agp-test/blob/741fc8741777d36c478458cf78f0f0bdfe8a29ec/makeflow/combined_workflow.jx

**Comment by julianpistorius** [comment]
@Chris-Schnaufer Now that things are working, do you want me to point the PR to this (AgPipeline/computing-pipeline) repository?
